name: Hello workflow

on:
  push:
    branches: [master]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: say Hello to users
        run: echo "Hello Everyone"

      - name: say hello to username
        run: echo "Hello $USER"

  details:
    runs-on: ubuntu-latest
    steps:
      - name: show versions
        run: docker --version && python --version
